# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 12:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('user', models.ManyToManyField(blank=True, default=None, null=True, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u0440\u043e\u0444\u0438\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430',
                'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('text', models.TextField(blank=True, null=True)),
                ('date_of_publish', models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 16, 12, 18, 11, 258767, tzinfo=utc), null=True, verbose_name='\u0414\u0430\u0442\u0430 \u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('date_of_start', models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 16, 12, 18, 11, 258821, tzinfo=utc), null=True, verbose_name='\u0414\u0430\u0442\u0430 \u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='note.Group', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430')),
                ('user', models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u0440\u043e\u0444\u0438\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u043f\u043e\u043c\u0438\u043d\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u041d\u0430\u043f\u043e\u043c\u0438\u043d\u0430\u043d\u0438\u0438',
            },
        ),
    ]
