# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 13:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20160816_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date_of_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 16, 13, 16, 15, 79438, tzinfo=utc), null=True, verbose_name='\u0414\u0430\u0442\u0430 \u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date_of_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 16, 13, 16, 15, 79491, tzinfo=utc), null=True, verbose_name='\u0414\u0430\u0442\u0430 \u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Group', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='reminder', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u0440\u043e\u0444\u0438\u043b\u044c'),
        ),
    ]
