# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20160817_1251'),
        ('komment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reminder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='note.Reminder'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_of_publish',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 17, 6, 51, 4, 954666, tzinfo=utc)),
        ),
    ]
