# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 07:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('komment', '0002_auto_20160817_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_of_publish',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 17, 7, 4, 24, 152456, tzinfo=utc)),
        ),
    ]
