# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('komment', '0004_auto_20160817_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_of_publish',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 17, 7, 8, 53, 847023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reminder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='note.Reminder'),
        ),
    ]
